#####################################################
## Purpose: Makefile for Chap_5_Basic_OOP/exercise5
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/29 19:03:47  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.1  2011/05/09 13:26:38  Greg
## Initial check-in
##
#####################################################
FILES = hdl/calc2_top.v design/shifter.v design/priority.v design/mux_out.v design/holdreg.v design/alu_output_stage.v design/alu_input_stage.v design/adder.v dut_env/classPackage.sv dut_env/dut_if.sv testBench.sv hdl/top.sv
TOPLEVEL = Top

include Makefile_non_DPI

